#!/bin/bash

apt-get install -y software-properties-common
add-apt-repository -y ppa:neovim-ppa/unstable
apt-get -y update
apt-get install -y python-software-properties python-dev python-pip \
    python3-dev python3-pip mosh exuberant-ctags ruby neovim
curl https://civiclabsconsulting.github.io/dotfiles/init.vim -o init.vim
mkdir -p ~/.config/nvim
mv init.vim ~/.config/nvim
pip install --upgrade neovim
pip2 install neovim
pip3 install neovim
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim -u ~/.config/nvim/init.vim "+set nomore" \
    "+PlugInstall!" \
    "+UpdateRemotePlugins" \
    "+qall"
