#!/bin/bash

U=vagrant

# OS package management
sudo apt-get install -y software-properties-common && \
    sudo add-apt-repository -y ppa:neovim-ppa/unstable && \
    sudo apt-get -y update

# OS dependencies
sudo apt-get install -y python-software-properties python-dev python-pip \
    python3-dev python3-pip mosh exuberant-ctags build-essential ruby \
    neovim ruby-dev tmux

# Nvim config
curl https://civiclabsconsulting.github.io/dotfiles/init.vim -o init.vim && \
    mkdir -p /home/$U/.config/nvim && mv init.vim /home/$U/.config/nvim

# Required Nvim Python modules
sudo pip2 install --upgrade neovim && \
    sudo pip3 install --upgrade neovim

# Required Nvim Ruby modules
sudo gem install neovim

# Nvim package management
sudo mkdir -p /home/$U/.local/share/nvim/site/autoload/ && \
    sudo chown $U -R /home/$U
sudo curl -fLo /home/$U/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Bootstrap
sudo nvim "+set nomore" \
    "+PlugInstall" \
    "+UpdateRemotePlugins" \
    "+qall"
