#!/bin/bash

# OS package management
sudo apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:neovim-ppa/unstable && \
    sudo apt-get -y update

# OS dependencies
sudo apt-get install -y python-software-properties python-dev python-pip \
    python3-dev python3-pip mosh exuberant-ctags ruby neovim

# Nvim config
curl https://civiclabsconsulting.github.io/dotfiles/init.vim -o init.vim && \
    mkdir -p ~/.config/nvim && mv init.vim ~/.config/nvim

# Required Nvim modules
sudo pip2 install --upgrade neovim && \
    sudo pip3 install --upgrade neovim

# Nvim package management
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Bootstrap
nvim -u ~/.config/nvim/init.vim "+set nomore" \
    "+PlugInstall!" \
    "+UpdateRemotePlugins!" \
    "+qall"
