#!/bin/bash

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:neovim-ppa/unstable
sudo apt-get -y update
sudo apt-get -y install neovim
sudo apt-get install -y python-software-properties python-dev python-pip \
    python3-dev python3-pip mosh
